### ISSUE TITLE
Error running eslint()

### ISSUE THREAD

**Issue by NachoSoto** [danpalmer/danger-plugin-eslint#1]
### `dangerfile.js`:
```js
import { danger } from 'danger';
import eslint from 'danger-plugin-eslint';

eslint();
```

### `.circleci/config.yml`:
```yml
version: 2
jobs:
  build:
    working_directory: ~/danger
    docker:
      - image: circleci/node:8.9.1
    steps:
      - checkout
      - run: npm install
      - run: yarn danger
```

### Output:
```
Error:  TypeError: Cannot read property 'messages' of undefined
    at /home/circleci/danger/node_modules/danger-plugin-eslint/dist/index.js:27:27
    at Generator.next (<anonymous>)
    at fulfilled (/home/circleci/danger/node_modules/danger-plugin-eslint/dist/index.js:4:58)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```
